### ISSUE TITLE
Loans query/facet - pending loans with no copies available

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-migrator-kit#110]
In the same way that we need to extract pending loan requests where an item is immediately available (issue reported already in https://github.com/CERNDocumentServer/cds-migrator-kit/issues/106)
we need to be able to filter pending loan requests where:
- there is no item at all or, 
-  all items have a status different from "Can Circulate" (i.e. Missing, Scanning, In Binding, For Reference Only) and "Not on loan". 

Which search query /facet can we do to achieve this?

**Comment by kprzerwa** [comment]
in the loans search page you can try:
`state:PENDING and available_items_for_loan_count:0`

**Comment by agentilb** [comment]
After having checked, the query doesn't fulfil the request: we need among those to identify the ones that are not available because of the status of the item and not because of their loan status. 
I.e. we need to identify immediately the loan requests that have no paper copy or where ALL paper copies have a status different from "Can Circulate" (i.e. Missing, Scanning, In Binding, For Reference Only)
I.e. https://sandbox-cds-ils.web.cern.ch/backoffice/loans/a8ksy-3p747

Because for those, we need to do an action (i.e. buy a new copy) otherwise the user will never have the book.
