### ISSUE TITLE
Books: Items: clean items data before migration

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-migrator-kit#18]
**TODO before migration**
---

**Libraries**

Some libraries need to be cleaned. This is the list of libraries **to keep**:

```
'163322','CERN Central Library','CH-1211 Geneva 23'
'1046','CERN LSL Library','CH-1211 Geneva 23'
'38875','CERN Depot 1, bldg. 2 (DE1)','CH-1211 Geneva 23, basement, building 2'
'49101','CERN Depot 2, bldg. 2 (DE2)','Basement, building 2'
'8070','CERN Depot 3, bldg. 2 (DE3)','Basement, building 2’
'15732','CERN Depot 4, bldg. 500-S-023 (DE4)',’'
'15156','CERN ARC Library','CH-1211 Geneva 23’
'167','CERN Didactic Library',’'
'4886','English Book Club','English Book Club'
- CERN TE-VSC Library
```

For these libraries, delete them but the attached items should be moved to **CERN Central Library**

```
- CERN Central Library BIB
- Same for Press Office
```

**Items**

1.  In legacy, items with `status`:
    * `scanning`: there will be a new list of items to bulk update items and set the status to `scanning`.
    * `cancelled`, `not arrived`, `untraceable`:  there should be 0 items with these statuses, so they should disappear
    * `not published`, `out of print`: to be kept

2. Ensure that the item without barcode has been fixed:
```
(('', 810479L, 12L, 'Periodical', '', '2014 vol.39 no.10', 'Reference', 'on shelf', datetime.datetime(2014, 9, 28, 14, 35, 35), datetime.datetime(2015, 3, 5, 10, 42, 27), 0L, ''),)
```

**Comment by ntarocco** [comment]
**What it has been done to clean up the data in production**

1. Some items deleted, list provided by the library
2. To decrease the number of item status:
  * `untraceable` -> `missing`
  * removed all items with status `cancelled` or `not arrived`

> Note: deleted data is stored in our `production scripts` folder.
