### ISSUE TITLE
Books: identify all records that need to be migrated

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-migrator-kit#19]
Based on the requirements, the following collections need to be migrated. Compute a query (or generate only one collection) in order to identify all records that need to be moved as part of the Books satellite.

| Collection | # of records |
  | --- | --- |
  | ~~[Books held by LHC](http://cds.cern.ch/collection/Books%20held%20by%20LHC)~~ (obsolete)|				~~0~~	|
  | ~~[Books held by PS-PO](http://cds.cern.ch/collection/Books%20held%20by%20PS-PO)~~ (obsolete)|				~~0~~|
  | ~~[Customary law](http://cds.cern.ch/collection/Customary%20law)~~ part of Legal Service Library |				~~2~~|
  | ~~[Highway Code](http://cds.cern.ch/collection/Highway%20Code)~~ part of Legal Service Library|				~~6~~|
  | ~~[Environmental Law](http://cds.cern.ch/collection/Environmental%20Law)~~ part of Legal Service Library|		~~7~~|
  | ~~[Law of research](http://cds.cern.ch/collection/Law%20of%20research)~~ part of Legal Service Library|		~~12~~|
  | ~~[Criminal Law](http://cds.cern.ch/collection/Criminal%20Law)~~ part of Legal Service Library|			~~21~~|
  | ~~[Nuclear Law](http://cds.cern.ch/collection/Nuclear%20Law)~~ part of Legal Service Library|			~~22~~|
  | ~~[Fiscal Law](http://cds.cern.ch/collection/Fiscal%20Law)~~ part of Legal Service Library|			~~24~~|
  | ~~[Social Security & Public Health](http://cds.cern.ch/collection/Social%20Security%20&%20Public%20Health)~~ part of Legal Service Library|				~~24~~|
  | ~~[Building Law](http://cds.cern.ch/collection/Building%20Law)~~ part of Legal Service Library|			~~36~~|
  | ~~[Legal Research](http://cds.cern.ch/collection/Legal%20Research)~~ part of Legal Service Library|			~~52~~|
  | ~~[Books held by EST](http://cds.cern.ch/collection/Books%20held%20by%20EST)~~ (obsolete)|			~~70~~|
  | ~~[Labour Law](http://cds.cern.ch/collection/Labour%20Law)~~ part of Legal Service Library|			~~75~~|
  | ~~[Books held by TIS](http://cds.cern.ch/collection/Books%20held%20by%20TIS)~~ (obsolete) |			~~104~~|
  | ~~[Public & Administrative Law](http://cds.cern.ch/collection/Public%20&%20Administrative%20Law)~~ part of Legal Service Library|	~~122~~|
  | ~~[Civil Law](http://cds.cern.ch/collection/Civil%20Law)~~ part of Legal Service Library|		~~211~~|
  | ~~[Pauli's scientific book collection](http://cds.cern.ch/collection/Pauli's%20scientific%20book%20collection)~~ to be moved with the Archives|			~~357~~|
  | ~~[International Law](http://cds.cern.ch/collection/International%20Law)~~ part of Legal Service Library|			~~530~~|
| [Book Proposals](http://cds.cern.ch/collection/Book%20Proposals)| 633|
  | [CERN Bookshop](http://cds.cern.ch/collection/CERN%20Bookshop) |			1049|
  | ~~[CERN Computing Bookshop](http://cds.cern.ch/collection/CERN%20Computing%20Bookshop)~~ (same as CERN Bookshop) |				~~1049~~ |
  | [Legal Service Library](http://cds.cern.ch/collection/Legal%20Service%20Library) |			1160|
|[CERN Yellow Reports](https://cds.cern.ch/collection/CERN%20Yellow%20Reports)|1183|
  | [Periodicals](http://cds.cern.ch/collection/Periodicals)-> different display, no individual items per volume|	2290	|
  | [English Book Club](http://cds.cern.ch/collection/English%20Book%20Club) |			4705|
  | ~~[UDC](http://cds.cern.ch/collection/UDC)~~ (marked as hidden)|		~~5667~~ |
  | [Standards](https://http://cds.cern.ch/collection/Books)|	12959|
  | [Proceedings](http://cds.cern.ch/collection/Proceedings) |			22973|
  | [eBooks](http://cds.cern.ch/collection/eBooks) |			81184|
  | [Books](https://http://cds.cern.ch/collection/Books) |				105341|

**Comment by ludmilamarian** [comment]
total number of records (23-10-2018 16:43): 161'952

**Comment by ludmilamarian** [comment]
I am trying to identify the correct query that will give us all the records that we need to move during the migration. I found 2 records: https://cds.cern.ch/record/1478620 and  https://cds.cern.ch/record/2145348 that are not part of any of the above collections, but they have the indicator Book. What shall we do with them?

**Comment by ludmilamarian** [comment]
as discussed, the `UDC` collection should not be migrated -> @agentilb shall we mark it as `hidden`?
This brings the total number of records to 156'285

**Comment by ludmilamarian** [comment]
the best that I could find for the query is:

`search_pattern(p='indicator:"english book club" OR indicator:BOOK OR indicator:STANDARD OR collection:PROCEEDINGS OR collection:PERI OR collection:PAULISCIENTIFICBOOK OR internalnote:"legal service library" OR media:ebook -980:deleted')`

This query though is not a perfect match with the union of all collections, I think because of some of the reports. This query returns ~500 results more than it should. (some example of record ids: `1285807, 1286045, 1286047, 1478620, 2036686, 2270978`)

Also, I think we should find a way not to rely on `media:ebook` (everything should already have one of the other indicators or collection tags). I think this is also because of some reports. There are currently 96 records that are tagged only with media:ebook but none of the other indicators or collection tags. (some example of record ids: `1988457, 1988461, 2066376, 2255181, 2255182, 2255183, 2255184, 2255185, 2255211`)

**Comment by agentilb** [comment]
Just one comment about the collections, some are obsolete and are not necessary anymore: 
Books held by LHC
Books held by PS-PO
Books held by EST
Books held by TIS
CERN Computing Bookshop (which is now CERN Bookshop)
I'm waiting an answer for all the collections within the LSL, but I believe they will have to be removed as well. 

For the periodicals, I need to update a bit the data model, the data model as I draw it was not meant for Periodicals, and therefore doesn't cover all the fields we use for periodicals.  

Yes, UDC can be marked as hidden.

The Pauli Scientific Books could be migrated with the other books, they are a specific collection though (should not be searchable within the normal book collection). They would have document type: book and collection: Pauli's scientific book collection

Indeed we should add the Book Suggestions. The search is 697C:BOOKSUGGESTION

Regarding the search you want to identify, do we need absolutely to do one single search? Or couldn't we go collection by collection to make sure we do not miss anything? 

Regarding the REPORTS, this is an absolute mess there, but thanks to the list of items, I can identify the ones that should be books or proceedings. Most of them should actually be preprints, and won't be part of this migration step. I'll do some cleaning next week, and let you know about the records you mentioned. 

Not sure it is indicated Not for circulation for the Standard collection. There are many items there. 
I think last time we met, we agreed that all items should have a '4 weeks loan' status.

**Comment by ludmilamarian** [comment]
For the `Books held by XX` are they already part of another collection or we will just mark them as obsolete (as UDC) and will never migrate them?

For the `Pauli Scientific Books`: do they have items attached? Otherwise, would it be better if they are part of the archives?

For the standards: I do not remember exactly, but maybe we were discussing that everything is for reference and nothing for loan? Or there will be items for loan as well?
Yes, all items will have a 4 weeks loan period, unless they are for reference. 

For the data model: I think it will be cleaner if we have another data model for periodicals and another one for standards, since their display is also going to be different. Basically, they can share a lot with the books, and then each individual type (book, standard, periodical, other?) can have their own "private" fields. 

For the search query: we will need to identify several queries (one per schema type: books, standards, periodicals). And by combining all the queries we can have one query of all records that need to be migrated. The goal is to have a query that joins together all collections. Trying to do that, I've noticed that sometimes data is not perfectly aligned with the collection (I pointed already some records that have some indicators or some collection tags, but not others, and this means that they are not part of any collection). The final goal is to make sure that we migrate every record part of the mentioned collections, but also, that we do not leave behind records that might not be in any of the above collections, that should have been migrated. 
In any case, at this point, having one query (even if not completely accurate) is useful for us to run some data cleaning on all the records (for example determining 035__9 tags) and to spot outliers.

**Comment by agentilb** [comment]
For the Books held by XX: I have cleaned them, so those collections should be empty hopefully (they should be anyway in Books or Proceedings. 

For the Pauli Scientific Books: indeed, they do not have items attached. We can put them in the Archive collection indeed, but the data model will be the same as for the books.

For the standards, they all should be 4 weeks loan.

Ok to have a separate data model for the periodicals, it makes sense indeed. I'be already one prepared. Do you need it already?
For the standards, the only field that differs compared to the books is the standard number (already included in the data model). But ok to have a different model if it is easier for you.

For the definition of the records to be migrated, this is indeed not easy, and as you, I discover many tricky cases... I'm now working on the cases you mentioned.

**Comment by ludmilamarian** [comment]
updated query `search_pattern(p='indicator:"english book club" OR indicator:BOOK OR indicator:STANDARD OR collection:PROCEEDINGS OR collection:PERI OR internalnote:"legal service library" OR media:ebook -980:deleted')`

@agentilb I understand that you are working on seeing which reports need to be added, which might have an impact on the query so I will leave this ticket opened until we figure out exactly the final configuration

**Comment by agentilb** [comment]
After checking the list of items included in the report collection, some 900 records have been moved to the Book collection (= added 690C_ $$aBOOK) so they will be migrated together with the others. 

Many items remain in the report collection, but they can be migrated in the second step. 

The query should include the collection: YELLOW REPORT. 
After some cleaning done on the collection, the criteria: media:ebook is not necessary in the query.

**Comment by ludmilamarian** [comment]
updated query `search_pattern(p='indicator:"english book club" OR indicator:BOOK OR indicator:STANDARD OR indicator:"YELLOW REPORT" OR collection:PROCEEDINGS OR collection:PERI OR internalnote:"legal service library" -980:deleted')`

**Comment by ludmilamarian** [comment]
Final query:

`search_pattern(p='690C_:BOOK OR 690C_:STANDARD OR 690C_:"YELLOW REPORT" OR 690C_:BOOKSUGGESTION OR 980__:PROCEEDINGS OR 980__:PERI OR 697C_:LEGSERLIB OR 697C_:"ENGLISH BOOK CLUB" -980__:DELETED')`
