### ISSUE TITLE
Series migration clean-up

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-migrator-kit#36]
- [x] fix the series similarity check on qa (is working locally, on qa it is not - probably due to python-leveinstein library which finds similarities)
- [x] remove 'View' button from the results of the series if they were already classified as a part of another - because they don't produce the file
- [x] make sure that nothing is missing from https://github.com/CERNDocumentServer/cds-dojson/issues/222 (it should be closed by a PR but it was not)
- [x] fix the failing tests on PR https://github.com/CERNDocumentServer/cds-migrator-kit/pull/35, merge to master and change deployment ref on openshift to master
- [x] make sure that migration script works (production script) and switch the membership of @agentilb to books-migrator-qa from books-migrator-dev openshift project

**Comment by kprzerwa** [comment]
https://github.com/CERNDocumentServer/cds-migrator-kit/issues/16 is ongoing (cleaning by the Library)

**Comment by equadon** [comment]
Discussion:
- Would it be useful instead of removing 'View' button (no. 2 on the list) and have 'View' link to the serial record that was created?

**Comment by equadon** [comment]
https://github.com/CERNDocumentServer/cds-dojson/issues/222 will be handled in https://github.com/CERNDocumentServer/cds-dojson/issues/242.
