### ISSUE TITLE
internal locations: health check

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-migrator-kit#54]
- [ ] check if all locations migrated (especially make sure that all internal/external were split correctly)
- [ ] check if addresses are correct

**Comment by agentilb** [comment]
Those libraries do not need to be migrated (they should be empty): 
CERN LHC Library
CERN SPS Library
CERN Group Library
CERN EP Library
CERN GL Library
CR1
LEP
CS
Other
English Book Club 
Amazon
Science Direct

Provide list of items for:
Press Office
CERN Courier
CERN TE-VSC Library

**Comment by agentilb** [comment]
Ticket created
