### ISSUE TITLE
multiparts: health check

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-migrator-kit#62]
- [ ] check if all multiparts migrated
- [ ] check if there is no empty multiparts
- [ ] check if all documents created
- [ ] check if documents of multiparts have attached correct items
- [ ] check if all fields are correct

**Comment by agentilb** [comment]
No item migrated:
https://sandbox-cds-ils.web.cern.ch/backoffice/documents/qjk9v-zyy59
https://cds.cern.ch/record/570932?ln=en
