### ISSUE TITLE
standards records: data cleaning on cds

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-migrator-kit#67]

**Comment by agentilb** [comment]
Change the  migration rule: 

- 084__c -> Subjects classification / Scheme: ICS / Subject value
- 962: Relation "other
- 962__b: record id of related field
- 962__k: relation "other" "is chapter of the book"

**Comment by agentilb** [comment]
Ticket created: https://github.com/CERNDocumentServer/cds-migrator-kit/issues/75
