### ISSUE TITLE
items: broken data on CDS

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-migrator-kit#73]
- [ ] item with barcode: P00025946 has \\ in the barcode field, remove "\\"
- [ ] item attached to recid 356068 has \\ instead of barcode and status missing. remove the item ?

**Comment by agentilb** [comment]
The first item has been deleted
The record 356068 is a deleted record, no items linked to deleted records should be migrated.

**Comment by kprzerwa** [comment]
> The first item has been deleted
> The record 356068 is a deleted record, no items linked to deleted records should be migrated.

I understand, it is not being migrated, but it causes an error in the script, because it is not valid barcode. It is easier to clean it from CDS than develop the code for this one one

**Comment by agentilb** [comment]
Cleaned.
