### ISSUE TITLE
Internal Location migration list of libraries not to be migrated

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-migrator-kit#76]
Those libraries do not need to be migrated (they are empty):
CERN LHC Library
CERN SPS Library
CERN Group Library
CERN EP Library
CERN GL Library
CR1
LEP
CS
Other
English Book Club
Amazon
Science Direct
Press Office
CERN Courier

**Comment by jrcastro2** [comment]
Updated [librariesFinalised.json](https://cernbox.cern.ch/index.php/apps/files/?dir=/__myprojects/digital-repositories/Services_Projects/CDS/CDS-ILS/Migration&#editor) removing the mentioned internal_locations.
