### ISSUE TITLE
Document: Migration comments

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-migrator-kit#77]
Examples of missing records in ILS, is it normal that they are not migrated? 
   - https://cds.cern.ch/record/2751122?ln=en
   - https://cds.cern.ch/record/2753916
   - https://cds.cern.ch/record/108270?ln=en
   - https://cds.cern.ch/record/2748755?ln=en
   - https://cds.cern.ch/record/2750030?ln=en
   - https://cds.cern.ch/record/1711476?ln=en
   - https://cds.cern.ch/record/2648929
   -  https://cds.cern.ch/record/2269044
   - https://cds.cern.ch/record/1083852?ln=en 
   - https://cds.cern.ch/record/113994?ln=en
   - https://cds.cern.ch/record/2748755?ln=en

Migration: 
- Creation date: last date of the modification of the record, can we take the 916 value instead? (ticket created)
- Publication date: random date, can we at least take January 1st? `(ticket created)`
- ISBN material not migrated. `(was fixed, not deployed yet)`
- Files not migrated? ex: https://sandbox-cds-ils.web.cern.ch/literature/x9azh-4az47 `(files migration is broken, i'm investigating)`
- Some URLs are missing: ex. https://sandbox-cds-ils.web.cern.ch/literature/7krys-57r79 `(there are broken links indeed, working on the solution)`
- Subject classification: correctly migrated, but when we open the form, it seems there is a problem with the Vocabularies. 
   - ex: https://sandbox-cds-ils.web.cern.ch/literature/52zvw-tcd45 (LoC and Dewey displayed, but if we open the form, there is an error) `(ticket created)`
-  Missing page_number in some records, where there is in CDS
     - https://sandbox-cds-ils.web.cern.ch/literature/b30r4-tdg66 / https://cds.cern.ch/record/2622172?ln=en  `(ticket created)`
 - Some records have a cover in CDS and not cover in Sandbox:
     -  ex: https://cds.cern.ch/record/2751375?ln=en / https://sandbox-cds-ils.web.cern.ch/literature/5kygx-61712
 - When there are several occurrences of the field 505, only one is kept: ex: https://sandbox-cds-ils.web.cern.ch/literature/h5wqy-3xr39 
-> Migration rule to be changed: Put together all 505 fields in the "table of content" field.   `(ticket created)`
 - Table of content (505): seems to be migrated but not displayed
Ex. https://sandbox-cds-ils.web.cern.ch/literature/evy0z-few54 (if we open the form, the table of content is there). `(ticket created)`

Questions:

- How (and why) is the status Periodical issue attributed? ex: https://sandbox-cds-ils.web.cern.ch/backoffice/documents/fw12k-fj091 
This document is a book, this distinction is not necessary for the users. 
- Publication information: as discussed earlier, we added the journal record information, will it be used to create a link between the document and the journal record?

**Comment by kprzerwa** [comment]
>  - Some records have a cover in CDS and not cover in Sandbox:
     -  ex: https://cds.cern.ch/record/2751375?ln=en / https://sandbox-cds-ils.web.cern.ch/literature/5kygx-61712
   
I didn't run covers script because it takes a lot of time and server resources to recreate them, we are checking the data at the moment

> How (and why) is the status Periodical issue attributed? ex: https://sandbox-cds-ils.web.cern.ch/backoffice/documents/fw12k-fj091 

Periodical issues are documents belonging to journal

> - Publication information: as discussed earlier, we added the journal record information, will it be used to create a link between the document and the journal record?

I didn't migrate the journals yet, so the relations are not there
