### ISSUE TITLE
Vendors: Migration issues

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-migrator-kit#95]
Duplicated entries: 
Examples: 
 - 2 vendors + 1 library: 
https://sandbox-cds-ils.web.cern.ch/backoffice/providers/7t27m-h7436
https://sandbox-cds-ils.web.cern.ch/backoffice/providers/kffq9-6cw07
https://sandbox-cds-ils.web.cern.ch/backoffice/providers/wgt2d-ahe70
- 1 vendor + 1 library
https://sandbox-cds-ils.web.cern.ch/backoffice/providers/w5qkq-rwj76
https://sandbox-cds-ils.web.cern.ch/backoffice/providers/c39pk-8cp16
 - 2 vendors :
https://sandbox-cds-ils.web.cern.ch/backoffice/providers/1bzhf-t9961
https://sandbox-cds-ils.web.cern.ch/backoffice/providers/985nm-ba115

- [x] Remove duplicates
- [x] When a provider is originally a vendor and a library, keep only library Library type.

**Comment by jrcastro2** [comment]
Updated `librariesFinalised.json` and `ACQ_vendor_0_finalised.json` in [cernbox](https://cernbox.cern.ch/index.php/apps/files/?dir=/__myprojects/digital-repositories/Services_Projects/CDS/CDS-ILS/Migration&).
